// Code generated by ent, DO NOT EDIT.

package packageversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the packageversion type in the database.
	Label = "package_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldIndexedAt holds the string denoting the indexedat field in the database.
	FieldIndexedAt = "indexed_at"
	// EdgePackage holds the string denoting the package edge name in mutations.
	EdgePackage = "Package"
	// Table holds the table name of the packageversion in the database.
	Table = "package_versions"
	// PackageTable is the table that holds the Package relation/edge.
	PackageTable = "package_versions"
	// PackageInverseTable is the table name for the SoftwarePackage entity.
	// It exists in this package in order to avoid circular dependency with the "softwarepackage" package.
	PackageInverseTable = "software_packages"
	// PackageColumn is the table column denoting the Package relation/edge.
	PackageColumn = "software_package_versions"
)

// Columns holds all SQL columns for packageversion fields.
var Columns = []string{
	FieldID,
	FieldVersion,
	FieldIndexedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "package_versions"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"software_package_versions",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultIndexedAt holds the default value on creation for the "IndexedAt" field.
	DefaultIndexedAt func() time.Time
)

// OrderOption defines the ordering options for the PackageVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByVersion orders the results by the Version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByIndexedAt orders the results by the IndexedAt field.
func ByIndexedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIndexedAt, opts...).ToFunc()
}

// ByPackageField orders the results by Package field.
func ByPackageField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPackageStep(), sql.OrderByField(field, opts...))
	}
}
func newPackageStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PackageInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PackageTable, PackageColumn),
	)
}
