// Code generated by ent, DO NOT EDIT.

package packageversion

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/d4t4l0r3/partial-mirror/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLTE(FieldID, id))
}

// Version applies equality check predicate on the "Version" field. It's identical to VersionEQ.
func Version(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldVersion, v))
}

// IndexedAt applies equality check predicate on the "IndexedAt" field. It's identical to IndexedAtEQ.
func IndexedAt(v time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldIndexedAt, v))
}

// VersionEQ applies the EQ predicate on the "Version" field.
func VersionEQ(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "Version" field.
func VersionNEQ(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "Version" field.
func VersionIn(vs ...string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "Version" field.
func VersionNotIn(vs ...string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "Version" field.
func VersionGT(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "Version" field.
func VersionGTE(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "Version" field.
func VersionLT(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "Version" field.
func VersionLTE(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLTE(FieldVersion, v))
}

// VersionContains applies the Contains predicate on the "Version" field.
func VersionContains(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldContains(FieldVersion, v))
}

// VersionHasPrefix applies the HasPrefix predicate on the "Version" field.
func VersionHasPrefix(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldHasPrefix(FieldVersion, v))
}

// VersionHasSuffix applies the HasSuffix predicate on the "Version" field.
func VersionHasSuffix(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldHasSuffix(FieldVersion, v))
}

// VersionEqualFold applies the EqualFold predicate on the "Version" field.
func VersionEqualFold(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEqualFold(FieldVersion, v))
}

// VersionContainsFold applies the ContainsFold predicate on the "Version" field.
func VersionContainsFold(v string) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldContainsFold(FieldVersion, v))
}

// IndexedAtEQ applies the EQ predicate on the "IndexedAt" field.
func IndexedAtEQ(v time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldEQ(FieldIndexedAt, v))
}

// IndexedAtNEQ applies the NEQ predicate on the "IndexedAt" field.
func IndexedAtNEQ(v time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNEQ(FieldIndexedAt, v))
}

// IndexedAtIn applies the In predicate on the "IndexedAt" field.
func IndexedAtIn(vs ...time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldIn(FieldIndexedAt, vs...))
}

// IndexedAtNotIn applies the NotIn predicate on the "IndexedAt" field.
func IndexedAtNotIn(vs ...time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldNotIn(FieldIndexedAt, vs...))
}

// IndexedAtGT applies the GT predicate on the "IndexedAt" field.
func IndexedAtGT(v time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGT(FieldIndexedAt, v))
}

// IndexedAtGTE applies the GTE predicate on the "IndexedAt" field.
func IndexedAtGTE(v time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldGTE(FieldIndexedAt, v))
}

// IndexedAtLT applies the LT predicate on the "IndexedAt" field.
func IndexedAtLT(v time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLT(FieldIndexedAt, v))
}

// IndexedAtLTE applies the LTE predicate on the "IndexedAt" field.
func IndexedAtLTE(v time.Time) predicate.PackageVersion {
	return predicate.PackageVersion(sql.FieldLTE(FieldIndexedAt, v))
}

// HasPackage applies the HasEdge predicate on the "Package" edge.
func HasPackage() predicate.PackageVersion {
	return predicate.PackageVersion(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PackageTable, PackageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPackageWith applies the HasEdge predicate on the "Package" edge with a given conditions (other predicates).
func HasPackageWith(preds ...predicate.SoftwarePackage) predicate.PackageVersion {
	return predicate.PackageVersion(func(s *sql.Selector) {
		step := newPackageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PackageVersion) predicate.PackageVersion {
	return predicate.PackageVersion(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PackageVersion) predicate.PackageVersion {
	return predicate.PackageVersion(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PackageVersion) predicate.PackageVersion {
	return predicate.PackageVersion(sql.NotPredicates(p))
}
