// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PackageVersionsColumns holds the columns for the "package_versions" table.
	PackageVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "version", Type: field.TypeString, Unique: true},
		{Name: "indexed_at", Type: field.TypeTime},
		{Name: "software_package_versions", Type: field.TypeInt, Nullable: true},
	}
	// PackageVersionsTable holds the schema information for the "package_versions" table.
	PackageVersionsTable = &schema.Table{
		Name:       "package_versions",
		Columns:    PackageVersionsColumns,
		PrimaryKey: []*schema.Column{PackageVersionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "package_versions_software_packages_Versions",
				Columns:    []*schema.Column{PackageVersionsColumns[3]},
				RefColumns: []*schema.Column{SoftwarePackagesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SoftwarePackagesColumns holds the columns for the "software_packages" table.
	SoftwarePackagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// SoftwarePackagesTable holds the schema information for the "software_packages" table.
	SoftwarePackagesTable = &schema.Table{
		Name:       "software_packages",
		Columns:    SoftwarePackagesColumns,
		PrimaryKey: []*schema.Column{SoftwarePackagesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PackageVersionsTable,
		SoftwarePackagesTable,
	}
)

func init() {
	PackageVersionsTable.ForeignKeys[0].RefTable = SoftwarePackagesTable
}
