// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/d4t4l0r3/partial-mirror/ent/packageversion"
	"github.com/d4t4l0r3/partial-mirror/ent/predicate"
	"github.com/d4t4l0r3/partial-mirror/ent/softwarepackage"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypePackageVersion  = "PackageVersion"
	TypeSoftwarePackage = "SoftwarePackage"
)

// PackageVersionMutation represents an operation that mutates the PackageVersion nodes in the graph.
type PackageVersionMutation struct {
	config
	op              Op
	typ             string
	id              *int
	_Version        *string
	_IndexedAt      *time.Time
	clearedFields   map[string]struct{}
	_Package        *int
	cleared_Package bool
	done            bool
	oldValue        func(context.Context) (*PackageVersion, error)
	predicates      []predicate.PackageVersion
}

var _ ent.Mutation = (*PackageVersionMutation)(nil)

// packageversionOption allows management of the mutation configuration using functional options.
type packageversionOption func(*PackageVersionMutation)

// newPackageVersionMutation creates new mutation for the PackageVersion entity.
func newPackageVersionMutation(c config, op Op, opts ...packageversionOption) *PackageVersionMutation {
	m := &PackageVersionMutation{
		config:        c,
		op:            op,
		typ:           TypePackageVersion,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withPackageVersionID sets the ID field of the mutation.
func withPackageVersionID(id int) packageversionOption {
	return func(m *PackageVersionMutation) {
		var (
			err   error
			once  sync.Once
			value *PackageVersion
		)
		m.oldValue = func(ctx context.Context) (*PackageVersion, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().PackageVersion.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withPackageVersion sets the old PackageVersion of the mutation.
func withPackageVersion(node *PackageVersion) packageversionOption {
	return func(m *PackageVersionMutation) {
		m.oldValue = func(context.Context) (*PackageVersion, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m PackageVersionMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m PackageVersionMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *PackageVersionMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *PackageVersionMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().PackageVersion.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetVersion sets the "Version" field.
func (m *PackageVersionMutation) SetVersion(s string) {
	m._Version = &s
}

// Version returns the value of the "Version" field in the mutation.
func (m *PackageVersionMutation) Version() (r string, exists bool) {
	v := m._Version
	if v == nil {
		return
	}
	return *v, true
}

// OldVersion returns the old "Version" field's value of the PackageVersion entity.
// If the PackageVersion object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PackageVersionMutation) OldVersion(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldVersion is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldVersion requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldVersion: %w", err)
	}
	return oldValue.Version, nil
}

// ResetVersion resets all changes to the "Version" field.
func (m *PackageVersionMutation) ResetVersion() {
	m._Version = nil
}

// SetIndexedAt sets the "IndexedAt" field.
func (m *PackageVersionMutation) SetIndexedAt(t time.Time) {
	m._IndexedAt = &t
}

// IndexedAt returns the value of the "IndexedAt" field in the mutation.
func (m *PackageVersionMutation) IndexedAt() (r time.Time, exists bool) {
	v := m._IndexedAt
	if v == nil {
		return
	}
	return *v, true
}

// OldIndexedAt returns the old "IndexedAt" field's value of the PackageVersion entity.
// If the PackageVersion object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *PackageVersionMutation) OldIndexedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldIndexedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldIndexedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldIndexedAt: %w", err)
	}
	return oldValue.IndexedAt, nil
}

// ResetIndexedAt resets all changes to the "IndexedAt" field.
func (m *PackageVersionMutation) ResetIndexedAt() {
	m._IndexedAt = nil
}

// SetPackageID sets the "Package" edge to the SoftwarePackage entity by id.
func (m *PackageVersionMutation) SetPackageID(id int) {
	m._Package = &id
}

// ClearPackage clears the "Package" edge to the SoftwarePackage entity.
func (m *PackageVersionMutation) ClearPackage() {
	m.cleared_Package = true
}

// PackageCleared reports if the "Package" edge to the SoftwarePackage entity was cleared.
func (m *PackageVersionMutation) PackageCleared() bool {
	return m.cleared_Package
}

// PackageID returns the "Package" edge ID in the mutation.
func (m *PackageVersionMutation) PackageID() (id int, exists bool) {
	if m._Package != nil {
		return *m._Package, true
	}
	return
}

// PackageIDs returns the "Package" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// PackageID instead. It exists only for internal usage by the builders.
func (m *PackageVersionMutation) PackageIDs() (ids []int) {
	if id := m._Package; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetPackage resets all changes to the "Package" edge.
func (m *PackageVersionMutation) ResetPackage() {
	m._Package = nil
	m.cleared_Package = false
}

// Where appends a list predicates to the PackageVersionMutation builder.
func (m *PackageVersionMutation) Where(ps ...predicate.PackageVersion) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the PackageVersionMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *PackageVersionMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.PackageVersion, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *PackageVersionMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *PackageVersionMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (PackageVersion).
func (m *PackageVersionMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *PackageVersionMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m._Version != nil {
		fields = append(fields, packageversion.FieldVersion)
	}
	if m._IndexedAt != nil {
		fields = append(fields, packageversion.FieldIndexedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *PackageVersionMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case packageversion.FieldVersion:
		return m.Version()
	case packageversion.FieldIndexedAt:
		return m.IndexedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *PackageVersionMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case packageversion.FieldVersion:
		return m.OldVersion(ctx)
	case packageversion.FieldIndexedAt:
		return m.OldIndexedAt(ctx)
	}
	return nil, fmt.Errorf("unknown PackageVersion field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PackageVersionMutation) SetField(name string, value ent.Value) error {
	switch name {
	case packageversion.FieldVersion:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetVersion(v)
		return nil
	case packageversion.FieldIndexedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetIndexedAt(v)
		return nil
	}
	return fmt.Errorf("unknown PackageVersion field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *PackageVersionMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *PackageVersionMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *PackageVersionMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown PackageVersion numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *PackageVersionMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *PackageVersionMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *PackageVersionMutation) ClearField(name string) error {
	return fmt.Errorf("unknown PackageVersion nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *PackageVersionMutation) ResetField(name string) error {
	switch name {
	case packageversion.FieldVersion:
		m.ResetVersion()
		return nil
	case packageversion.FieldIndexedAt:
		m.ResetIndexedAt()
		return nil
	}
	return fmt.Errorf("unknown PackageVersion field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *PackageVersionMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m._Package != nil {
		edges = append(edges, packageversion.EdgePackage)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *PackageVersionMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case packageversion.EdgePackage:
		if id := m._Package; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *PackageVersionMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *PackageVersionMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *PackageVersionMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.cleared_Package {
		edges = append(edges, packageversion.EdgePackage)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *PackageVersionMutation) EdgeCleared(name string) bool {
	switch name {
	case packageversion.EdgePackage:
		return m.cleared_Package
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *PackageVersionMutation) ClearEdge(name string) error {
	switch name {
	case packageversion.EdgePackage:
		m.ClearPackage()
		return nil
	}
	return fmt.Errorf("unknown PackageVersion unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *PackageVersionMutation) ResetEdge(name string) error {
	switch name {
	case packageversion.EdgePackage:
		m.ResetPackage()
		return nil
	}
	return fmt.Errorf("unknown PackageVersion edge %s", name)
}

// SoftwarePackageMutation represents an operation that mutates the SoftwarePackage nodes in the graph.
type SoftwarePackageMutation struct {
	config
	op               Op
	typ              string
	id               *int
	name             *string
	clearedFields    map[string]struct{}
	_Versions        map[int]struct{}
	removed_Versions map[int]struct{}
	cleared_Versions bool
	done             bool
	oldValue         func(context.Context) (*SoftwarePackage, error)
	predicates       []predicate.SoftwarePackage
}

var _ ent.Mutation = (*SoftwarePackageMutation)(nil)

// softwarepackageOption allows management of the mutation configuration using functional options.
type softwarepackageOption func(*SoftwarePackageMutation)

// newSoftwarePackageMutation creates new mutation for the SoftwarePackage entity.
func newSoftwarePackageMutation(c config, op Op, opts ...softwarepackageOption) *SoftwarePackageMutation {
	m := &SoftwarePackageMutation{
		config:        c,
		op:            op,
		typ:           TypeSoftwarePackage,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSoftwarePackageID sets the ID field of the mutation.
func withSoftwarePackageID(id int) softwarepackageOption {
	return func(m *SoftwarePackageMutation) {
		var (
			err   error
			once  sync.Once
			value *SoftwarePackage
		)
		m.oldValue = func(ctx context.Context) (*SoftwarePackage, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().SoftwarePackage.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSoftwarePackage sets the old SoftwarePackage of the mutation.
func withSoftwarePackage(node *SoftwarePackage) softwarepackageOption {
	return func(m *SoftwarePackageMutation) {
		m.oldValue = func(context.Context) (*SoftwarePackage, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SoftwarePackageMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SoftwarePackageMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SoftwarePackageMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SoftwarePackageMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().SoftwarePackage.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *SoftwarePackageMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *SoftwarePackageMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the SoftwarePackage entity.
// If the SoftwarePackage object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SoftwarePackageMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *SoftwarePackageMutation) ResetName() {
	m.name = nil
}

// AddVersionIDs adds the "Versions" edge to the PackageVersion entity by ids.
func (m *SoftwarePackageMutation) AddVersionIDs(ids ...int) {
	if m._Versions == nil {
		m._Versions = make(map[int]struct{})
	}
	for i := range ids {
		m._Versions[ids[i]] = struct{}{}
	}
}

// ClearVersions clears the "Versions" edge to the PackageVersion entity.
func (m *SoftwarePackageMutation) ClearVersions() {
	m.cleared_Versions = true
}

// VersionsCleared reports if the "Versions" edge to the PackageVersion entity was cleared.
func (m *SoftwarePackageMutation) VersionsCleared() bool {
	return m.cleared_Versions
}

// RemoveVersionIDs removes the "Versions" edge to the PackageVersion entity by IDs.
func (m *SoftwarePackageMutation) RemoveVersionIDs(ids ...int) {
	if m.removed_Versions == nil {
		m.removed_Versions = make(map[int]struct{})
	}
	for i := range ids {
		delete(m._Versions, ids[i])
		m.removed_Versions[ids[i]] = struct{}{}
	}
}

// RemovedVersions returns the removed IDs of the "Versions" edge to the PackageVersion entity.
func (m *SoftwarePackageMutation) RemovedVersionsIDs() (ids []int) {
	for id := range m.removed_Versions {
		ids = append(ids, id)
	}
	return
}

// VersionsIDs returns the "Versions" edge IDs in the mutation.
func (m *SoftwarePackageMutation) VersionsIDs() (ids []int) {
	for id := range m._Versions {
		ids = append(ids, id)
	}
	return
}

// ResetVersions resets all changes to the "Versions" edge.
func (m *SoftwarePackageMutation) ResetVersions() {
	m._Versions = nil
	m.cleared_Versions = false
	m.removed_Versions = nil
}

// Where appends a list predicates to the SoftwarePackageMutation builder.
func (m *SoftwarePackageMutation) Where(ps ...predicate.SoftwarePackage) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SoftwarePackageMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SoftwarePackageMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.SoftwarePackage, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SoftwarePackageMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SoftwarePackageMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (SoftwarePackage).
func (m *SoftwarePackageMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SoftwarePackageMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.name != nil {
		fields = append(fields, softwarepackage.FieldName)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SoftwarePackageMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case softwarepackage.FieldName:
		return m.Name()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SoftwarePackageMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case softwarepackage.FieldName:
		return m.OldName(ctx)
	}
	return nil, fmt.Errorf("unknown SoftwarePackage field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SoftwarePackageMutation) SetField(name string, value ent.Value) error {
	switch name {
	case softwarepackage.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	}
	return fmt.Errorf("unknown SoftwarePackage field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SoftwarePackageMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SoftwarePackageMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SoftwarePackageMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown SoftwarePackage numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SoftwarePackageMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SoftwarePackageMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SoftwarePackageMutation) ClearField(name string) error {
	return fmt.Errorf("unknown SoftwarePackage nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SoftwarePackageMutation) ResetField(name string) error {
	switch name {
	case softwarepackage.FieldName:
		m.ResetName()
		return nil
	}
	return fmt.Errorf("unknown SoftwarePackage field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SoftwarePackageMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m._Versions != nil {
		edges = append(edges, softwarepackage.EdgeVersions)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SoftwarePackageMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case softwarepackage.EdgeVersions:
		ids := make([]ent.Value, 0, len(m._Versions))
		for id := range m._Versions {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SoftwarePackageMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removed_Versions != nil {
		edges = append(edges, softwarepackage.EdgeVersions)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SoftwarePackageMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case softwarepackage.EdgeVersions:
		ids := make([]ent.Value, 0, len(m.removed_Versions))
		for id := range m.removed_Versions {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SoftwarePackageMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.cleared_Versions {
		edges = append(edges, softwarepackage.EdgeVersions)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SoftwarePackageMutation) EdgeCleared(name string) bool {
	switch name {
	case softwarepackage.EdgeVersions:
		return m.cleared_Versions
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SoftwarePackageMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown SoftwarePackage unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SoftwarePackageMutation) ResetEdge(name string) error {
	switch name {
	case softwarepackage.EdgeVersions:
		m.ResetVersions()
		return nil
	}
	return fmt.Errorf("unknown SoftwarePackage edge %s", name)
}
