// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/d4t4l0r3/partial-mirror/ent/packageversion"
	"github.com/d4t4l0r3/partial-mirror/ent/predicate"
	"github.com/d4t4l0r3/partial-mirror/ent/softwarepackage"
)

// PackageVersionUpdate is the builder for updating PackageVersion entities.
type PackageVersionUpdate struct {
	config
	hooks    []Hook
	mutation *PackageVersionMutation
}

// Where appends a list predicates to the PackageVersionUpdate builder.
func (_u *PackageVersionUpdate) Where(ps ...predicate.PackageVersion) *PackageVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetVersion sets the "Version" field.
func (_u *PackageVersionUpdate) SetVersion(v string) *PackageVersionUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "Version" field if the given value is not nil.
func (_u *PackageVersionUpdate) SetNillableVersion(v *string) *PackageVersionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetIndexedAt sets the "IndexedAt" field.
func (_u *PackageVersionUpdate) SetIndexedAt(v time.Time) *PackageVersionUpdate {
	_u.mutation.SetIndexedAt(v)
	return _u
}

// SetNillableIndexedAt sets the "IndexedAt" field if the given value is not nil.
func (_u *PackageVersionUpdate) SetNillableIndexedAt(v *time.Time) *PackageVersionUpdate {
	if v != nil {
		_u.SetIndexedAt(*v)
	}
	return _u
}

// SetPackageID sets the "Package" edge to the SoftwarePackage entity by ID.
func (_u *PackageVersionUpdate) SetPackageID(id int) *PackageVersionUpdate {
	_u.mutation.SetPackageID(id)
	return _u
}

// SetNillablePackageID sets the "Package" edge to the SoftwarePackage entity by ID if the given value is not nil.
func (_u *PackageVersionUpdate) SetNillablePackageID(id *int) *PackageVersionUpdate {
	if id != nil {
		_u = _u.SetPackageID(*id)
	}
	return _u
}

// SetPackage sets the "Package" edge to the SoftwarePackage entity.
func (_u *PackageVersionUpdate) SetPackage(v *SoftwarePackage) *PackageVersionUpdate {
	return _u.SetPackageID(v.ID)
}

// Mutation returns the PackageVersionMutation object of the builder.
func (_u *PackageVersionUpdate) Mutation() *PackageVersionMutation {
	return _u.mutation
}

// ClearPackage clears the "Package" edge to the SoftwarePackage entity.
func (_u *PackageVersionUpdate) ClearPackage() *PackageVersionUpdate {
	_u.mutation.ClearPackage()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PackageVersionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PackageVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PackageVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PackageVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PackageVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(packageversion.Table, packageversion.Columns, sqlgraph.NewFieldSpec(packageversion.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(packageversion.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.IndexedAt(); ok {
		_spec.SetField(packageversion.FieldIndexedAt, field.TypeTime, value)
	}
	if _u.mutation.PackageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   packageversion.PackageTable,
			Columns: []string{packageversion.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(softwarepackage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PackageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   packageversion.PackageTable,
			Columns: []string{packageversion.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(softwarepackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{packageversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PackageVersionUpdateOne is the builder for updating a single PackageVersion entity.
type PackageVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PackageVersionMutation
}

// SetVersion sets the "Version" field.
func (_u *PackageVersionUpdateOne) SetVersion(v string) *PackageVersionUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "Version" field if the given value is not nil.
func (_u *PackageVersionUpdateOne) SetNillableVersion(v *string) *PackageVersionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetIndexedAt sets the "IndexedAt" field.
func (_u *PackageVersionUpdateOne) SetIndexedAt(v time.Time) *PackageVersionUpdateOne {
	_u.mutation.SetIndexedAt(v)
	return _u
}

// SetNillableIndexedAt sets the "IndexedAt" field if the given value is not nil.
func (_u *PackageVersionUpdateOne) SetNillableIndexedAt(v *time.Time) *PackageVersionUpdateOne {
	if v != nil {
		_u.SetIndexedAt(*v)
	}
	return _u
}

// SetPackageID sets the "Package" edge to the SoftwarePackage entity by ID.
func (_u *PackageVersionUpdateOne) SetPackageID(id int) *PackageVersionUpdateOne {
	_u.mutation.SetPackageID(id)
	return _u
}

// SetNillablePackageID sets the "Package" edge to the SoftwarePackage entity by ID if the given value is not nil.
func (_u *PackageVersionUpdateOne) SetNillablePackageID(id *int) *PackageVersionUpdateOne {
	if id != nil {
		_u = _u.SetPackageID(*id)
	}
	return _u
}

// SetPackage sets the "Package" edge to the SoftwarePackage entity.
func (_u *PackageVersionUpdateOne) SetPackage(v *SoftwarePackage) *PackageVersionUpdateOne {
	return _u.SetPackageID(v.ID)
}

// Mutation returns the PackageVersionMutation object of the builder.
func (_u *PackageVersionUpdateOne) Mutation() *PackageVersionMutation {
	return _u.mutation
}

// ClearPackage clears the "Package" edge to the SoftwarePackage entity.
func (_u *PackageVersionUpdateOne) ClearPackage() *PackageVersionUpdateOne {
	_u.mutation.ClearPackage()
	return _u
}

// Where appends a list predicates to the PackageVersionUpdate builder.
func (_u *PackageVersionUpdateOne) Where(ps ...predicate.PackageVersion) *PackageVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PackageVersionUpdateOne) Select(field string, fields ...string) *PackageVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PackageVersion entity.
func (_u *PackageVersionUpdateOne) Save(ctx context.Context) (*PackageVersion, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PackageVersionUpdateOne) SaveX(ctx context.Context) *PackageVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PackageVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PackageVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PackageVersionUpdateOne) sqlSave(ctx context.Context) (_node *PackageVersion, err error) {
	_spec := sqlgraph.NewUpdateSpec(packageversion.Table, packageversion.Columns, sqlgraph.NewFieldSpec(packageversion.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PackageVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, packageversion.FieldID)
		for _, f := range fields {
			if !packageversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != packageversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(packageversion.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.IndexedAt(); ok {
		_spec.SetField(packageversion.FieldIndexedAt, field.TypeTime, value)
	}
	if _u.mutation.PackageCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   packageversion.PackageTable,
			Columns: []string{packageversion.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(softwarepackage.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PackageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   packageversion.PackageTable,
			Columns: []string{packageversion.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(softwarepackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PackageVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{packageversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
