// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/d4t4l0r3/partial-mirror/ent/packageversion"
	"github.com/d4t4l0r3/partial-mirror/ent/softwarepackage"
)

// PackageVersionCreate is the builder for creating a PackageVersion entity.
type PackageVersionCreate struct {
	config
	mutation *PackageVersionMutation
	hooks    []Hook
}

// SetVersion sets the "Version" field.
func (_c *PackageVersionCreate) SetVersion(v string) *PackageVersionCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetIndexedAt sets the "IndexedAt" field.
func (_c *PackageVersionCreate) SetIndexedAt(v time.Time) *PackageVersionCreate {
	_c.mutation.SetIndexedAt(v)
	return _c
}

// SetNillableIndexedAt sets the "IndexedAt" field if the given value is not nil.
func (_c *PackageVersionCreate) SetNillableIndexedAt(v *time.Time) *PackageVersionCreate {
	if v != nil {
		_c.SetIndexedAt(*v)
	}
	return _c
}

// SetPackageID sets the "Package" edge to the SoftwarePackage entity by ID.
func (_c *PackageVersionCreate) SetPackageID(id int) *PackageVersionCreate {
	_c.mutation.SetPackageID(id)
	return _c
}

// SetNillablePackageID sets the "Package" edge to the SoftwarePackage entity by ID if the given value is not nil.
func (_c *PackageVersionCreate) SetNillablePackageID(id *int) *PackageVersionCreate {
	if id != nil {
		_c = _c.SetPackageID(*id)
	}
	return _c
}

// SetPackage sets the "Package" edge to the SoftwarePackage entity.
func (_c *PackageVersionCreate) SetPackage(v *SoftwarePackage) *PackageVersionCreate {
	return _c.SetPackageID(v.ID)
}

// Mutation returns the PackageVersionMutation object of the builder.
func (_c *PackageVersionCreate) Mutation() *PackageVersionMutation {
	return _c.mutation
}

// Save creates the PackageVersion in the database.
func (_c *PackageVersionCreate) Save(ctx context.Context) (*PackageVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PackageVersionCreate) SaveX(ctx context.Context) *PackageVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PackageVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PackageVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PackageVersionCreate) defaults() {
	if _, ok := _c.mutation.IndexedAt(); !ok {
		v := packageversion.DefaultIndexedAt()
		_c.mutation.SetIndexedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PackageVersionCreate) check() error {
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "Version", err: errors.New(`ent: missing required field "PackageVersion.Version"`)}
	}
	if _, ok := _c.mutation.IndexedAt(); !ok {
		return &ValidationError{Name: "IndexedAt", err: errors.New(`ent: missing required field "PackageVersion.IndexedAt"`)}
	}
	return nil
}

func (_c *PackageVersionCreate) sqlSave(ctx context.Context) (*PackageVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PackageVersionCreate) createSpec() (*PackageVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &PackageVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(packageversion.Table, sqlgraph.NewFieldSpec(packageversion.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(packageversion.FieldVersion, field.TypeString, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.IndexedAt(); ok {
		_spec.SetField(packageversion.FieldIndexedAt, field.TypeTime, value)
		_node.IndexedAt = value
	}
	if nodes := _c.mutation.PackageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   packageversion.PackageTable,
			Columns: []string{packageversion.PackageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(softwarepackage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.software_package_versions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PackageVersionCreateBulk is the builder for creating many PackageVersion entities in bulk.
type PackageVersionCreateBulk struct {
	config
	err      error
	builders []*PackageVersionCreate
}

// Save creates the PackageVersion entities in the database.
func (_c *PackageVersionCreateBulk) Save(ctx context.Context) ([]*PackageVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PackageVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PackageVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PackageVersionCreateBulk) SaveX(ctx context.Context) []*PackageVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PackageVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PackageVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
