// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/d4t4l0r3/partial-mirror/ent/packageversion"
	"github.com/d4t4l0r3/partial-mirror/ent/softwarepackage"
)

// PackageVersion is the model entity for the PackageVersion schema.
type PackageVersion struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Version holds the value of the "Version" field.
	Version string `json:"Version,omitempty"`
	// IndexedAt holds the value of the "IndexedAt" field.
	IndexedAt time.Time `json:"IndexedAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PackageVersionQuery when eager-loading is set.
	Edges                     PackageVersionEdges `json:"edges"`
	software_package_versions *int
	selectValues              sql.SelectValues
}

// PackageVersionEdges holds the relations/edges for other nodes in the graph.
type PackageVersionEdges struct {
	// Package holds the value of the Package edge.
	Package *SoftwarePackage `json:"Package,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PackageOrErr returns the Package value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PackageVersionEdges) PackageOrErr() (*SoftwarePackage, error) {
	if e.Package != nil {
		return e.Package, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: softwarepackage.Label}
	}
	return nil, &NotLoadedError{edge: "Package"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PackageVersion) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case packageversion.FieldID:
			values[i] = new(sql.NullInt64)
		case packageversion.FieldVersion:
			values[i] = new(sql.NullString)
		case packageversion.FieldIndexedAt:
			values[i] = new(sql.NullTime)
		case packageversion.ForeignKeys[0]: // software_package_versions
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PackageVersion fields.
func (_m *PackageVersion) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case packageversion.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case packageversion.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case packageversion.FieldIndexedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field IndexedAt", values[i])
			} else if value.Valid {
				_m.IndexedAt = value.Time
			}
		case packageversion.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field software_package_versions", value)
			} else if value.Valid {
				_m.software_package_versions = new(int)
				*_m.software_package_versions = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PackageVersion.
// This includes values selected through modifiers, order, etc.
func (_m *PackageVersion) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPackage queries the "Package" edge of the PackageVersion entity.
func (_m *PackageVersion) QueryPackage() *SoftwarePackageQuery {
	return NewPackageVersionClient(_m.config).QueryPackage(_m)
}

// Update returns a builder for updating this PackageVersion.
// Note that you need to call PackageVersion.Unwrap() before calling this method if this PackageVersion
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PackageVersion) Update() *PackageVersionUpdateOne {
	return NewPackageVersionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PackageVersion entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PackageVersion) Unwrap() *PackageVersion {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PackageVersion is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PackageVersion) String() string {
	var builder strings.Builder
	builder.WriteString("PackageVersion(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("Version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("IndexedAt=")
	builder.WriteString(_m.IndexedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PackageVersions is a parsable slice of PackageVersion.
type PackageVersions []*PackageVersion
