// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/d4t4l0r3/partial-mirror/ent/packageversion"
	"github.com/d4t4l0r3/partial-mirror/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	packageversionFields := schema.PackageVersion{}.Fields()
	_ = packageversionFields
	// packageversionDescIndexedAt is the schema descriptor for IndexedAt field.
	packageversionDescIndexedAt := packageversionFields[1].Descriptor()
	// packageversion.DefaultIndexedAt holds the default value on creation for the IndexedAt field.
	packageversion.DefaultIndexedAt = packageversionDescIndexedAt.Default.(func() time.Time)
}
