// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/d4t4l0r3/partial-mirror/ent/packageversion"
	"github.com/d4t4l0r3/partial-mirror/ent/predicate"
	"github.com/d4t4l0r3/partial-mirror/ent/softwarepackage"
)

// SoftwarePackageUpdate is the builder for updating SoftwarePackage entities.
type SoftwarePackageUpdate struct {
	config
	hooks    []Hook
	mutation *SoftwarePackageMutation
}

// Where appends a list predicates to the SoftwarePackageUpdate builder.
func (_u *SoftwarePackageUpdate) Where(ps ...predicate.SoftwarePackage) *SoftwarePackageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SoftwarePackageUpdate) SetName(v string) *SoftwarePackageUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SoftwarePackageUpdate) SetNillableName(v *string) *SoftwarePackageUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddVersionIDs adds the "Versions" edge to the PackageVersion entity by IDs.
func (_u *SoftwarePackageUpdate) AddVersionIDs(ids ...int) *SoftwarePackageUpdate {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "Versions" edges to the PackageVersion entity.
func (_u *SoftwarePackageUpdate) AddVersions(v ...*PackageVersion) *SoftwarePackageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// Mutation returns the SoftwarePackageMutation object of the builder.
func (_u *SoftwarePackageUpdate) Mutation() *SoftwarePackageMutation {
	return _u.mutation
}

// ClearVersions clears all "Versions" edges to the PackageVersion entity.
func (_u *SoftwarePackageUpdate) ClearVersions() *SoftwarePackageUpdate {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "Versions" edge to PackageVersion entities by IDs.
func (_u *SoftwarePackageUpdate) RemoveVersionIDs(ids ...int) *SoftwarePackageUpdate {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "Versions" edges to PackageVersion entities.
func (_u *SoftwarePackageUpdate) RemoveVersions(v ...*PackageVersion) *SoftwarePackageUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SoftwarePackageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SoftwarePackageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SoftwarePackageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SoftwarePackageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SoftwarePackageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(softwarepackage.Table, softwarepackage.Columns, sqlgraph.NewFieldSpec(softwarepackage.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(softwarepackage.FieldName, field.TypeString, value)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   softwarepackage.VersionsTable,
			Columns: []string{softwarepackage.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packageversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   softwarepackage.VersionsTable,
			Columns: []string{softwarepackage.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packageversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   softwarepackage.VersionsTable,
			Columns: []string{softwarepackage.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packageversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{softwarepackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SoftwarePackageUpdateOne is the builder for updating a single SoftwarePackage entity.
type SoftwarePackageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SoftwarePackageMutation
}

// SetName sets the "name" field.
func (_u *SoftwarePackageUpdateOne) SetName(v string) *SoftwarePackageUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SoftwarePackageUpdateOne) SetNillableName(v *string) *SoftwarePackageUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// AddVersionIDs adds the "Versions" edge to the PackageVersion entity by IDs.
func (_u *SoftwarePackageUpdateOne) AddVersionIDs(ids ...int) *SoftwarePackageUpdateOne {
	_u.mutation.AddVersionIDs(ids...)
	return _u
}

// AddVersions adds the "Versions" edges to the PackageVersion entity.
func (_u *SoftwarePackageUpdateOne) AddVersions(v ...*PackageVersion) *SoftwarePackageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVersionIDs(ids...)
}

// Mutation returns the SoftwarePackageMutation object of the builder.
func (_u *SoftwarePackageUpdateOne) Mutation() *SoftwarePackageMutation {
	return _u.mutation
}

// ClearVersions clears all "Versions" edges to the PackageVersion entity.
func (_u *SoftwarePackageUpdateOne) ClearVersions() *SoftwarePackageUpdateOne {
	_u.mutation.ClearVersions()
	return _u
}

// RemoveVersionIDs removes the "Versions" edge to PackageVersion entities by IDs.
func (_u *SoftwarePackageUpdateOne) RemoveVersionIDs(ids ...int) *SoftwarePackageUpdateOne {
	_u.mutation.RemoveVersionIDs(ids...)
	return _u
}

// RemoveVersions removes "Versions" edges to PackageVersion entities.
func (_u *SoftwarePackageUpdateOne) RemoveVersions(v ...*PackageVersion) *SoftwarePackageUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVersionIDs(ids...)
}

// Where appends a list predicates to the SoftwarePackageUpdate builder.
func (_u *SoftwarePackageUpdateOne) Where(ps ...predicate.SoftwarePackage) *SoftwarePackageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SoftwarePackageUpdateOne) Select(field string, fields ...string) *SoftwarePackageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SoftwarePackage entity.
func (_u *SoftwarePackageUpdateOne) Save(ctx context.Context) (*SoftwarePackage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SoftwarePackageUpdateOne) SaveX(ctx context.Context) *SoftwarePackage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SoftwarePackageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SoftwarePackageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SoftwarePackageUpdateOne) sqlSave(ctx context.Context) (_node *SoftwarePackage, err error) {
	_spec := sqlgraph.NewUpdateSpec(softwarepackage.Table, softwarepackage.Columns, sqlgraph.NewFieldSpec(softwarepackage.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SoftwarePackage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, softwarepackage.FieldID)
		for _, f := range fields {
			if !softwarepackage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != softwarepackage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(softwarepackage.FieldName, field.TypeString, value)
	}
	if _u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   softwarepackage.VersionsTable,
			Columns: []string{softwarepackage.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packageversion.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVersionsIDs(); len(nodes) > 0 && !_u.mutation.VersionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   softwarepackage.VersionsTable,
			Columns: []string{softwarepackage.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packageversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VersionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   softwarepackage.VersionsTable,
			Columns: []string{softwarepackage.VersionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(packageversion.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SoftwarePackage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{softwarepackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
