// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/d4t4l0r3/partial-mirror/ent/packageversion"
	"github.com/d4t4l0r3/partial-mirror/ent/predicate"
	"github.com/d4t4l0r3/partial-mirror/ent/softwarepackage"
)

// SoftwarePackageQuery is the builder for querying SoftwarePackage entities.
type SoftwarePackageQuery struct {
	config
	ctx          *QueryContext
	order        []softwarepackage.OrderOption
	inters       []Interceptor
	predicates   []predicate.SoftwarePackage
	withVersions *PackageVersionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SoftwarePackageQuery builder.
func (_q *SoftwarePackageQuery) Where(ps ...predicate.SoftwarePackage) *SoftwarePackageQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SoftwarePackageQuery) Limit(limit int) *SoftwarePackageQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SoftwarePackageQuery) Offset(offset int) *SoftwarePackageQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SoftwarePackageQuery) Unique(unique bool) *SoftwarePackageQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SoftwarePackageQuery) Order(o ...softwarepackage.OrderOption) *SoftwarePackageQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryVersions chains the current query on the "Versions" edge.
func (_q *SoftwarePackageQuery) QueryVersions() *PackageVersionQuery {
	query := (&PackageVersionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(softwarepackage.Table, softwarepackage.FieldID, selector),
			sqlgraph.To(packageversion.Table, packageversion.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, softwarepackage.VersionsTable, softwarepackage.VersionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SoftwarePackage entity from the query.
// Returns a *NotFoundError when no SoftwarePackage was found.
func (_q *SoftwarePackageQuery) First(ctx context.Context) (*SoftwarePackage, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{softwarepackage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SoftwarePackageQuery) FirstX(ctx context.Context) *SoftwarePackage {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SoftwarePackage ID from the query.
// Returns a *NotFoundError when no SoftwarePackage ID was found.
func (_q *SoftwarePackageQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{softwarepackage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SoftwarePackageQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SoftwarePackage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SoftwarePackage entity is found.
// Returns a *NotFoundError when no SoftwarePackage entities are found.
func (_q *SoftwarePackageQuery) Only(ctx context.Context) (*SoftwarePackage, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{softwarepackage.Label}
	default:
		return nil, &NotSingularError{softwarepackage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SoftwarePackageQuery) OnlyX(ctx context.Context) *SoftwarePackage {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SoftwarePackage ID in the query.
// Returns a *NotSingularError when more than one SoftwarePackage ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SoftwarePackageQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{softwarepackage.Label}
	default:
		err = &NotSingularError{softwarepackage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SoftwarePackageQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SoftwarePackages.
func (_q *SoftwarePackageQuery) All(ctx context.Context) ([]*SoftwarePackage, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SoftwarePackage, *SoftwarePackageQuery]()
	return withInterceptors[[]*SoftwarePackage](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SoftwarePackageQuery) AllX(ctx context.Context) []*SoftwarePackage {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SoftwarePackage IDs.
func (_q *SoftwarePackageQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(softwarepackage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SoftwarePackageQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SoftwarePackageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SoftwarePackageQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SoftwarePackageQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SoftwarePackageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SoftwarePackageQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SoftwarePackageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SoftwarePackageQuery) Clone() *SoftwarePackageQuery {
	if _q == nil {
		return nil
	}
	return &SoftwarePackageQuery{
		config:       _q.config,
		ctx:          _q.ctx.Clone(),
		order:        append([]softwarepackage.OrderOption{}, _q.order...),
		inters:       append([]Interceptor{}, _q.inters...),
		predicates:   append([]predicate.SoftwarePackage{}, _q.predicates...),
		withVersions: _q.withVersions.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithVersions tells the query-builder to eager-load the nodes that are connected to
// the "Versions" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *SoftwarePackageQuery) WithVersions(opts ...func(*PackageVersionQuery)) *SoftwarePackageQuery {
	query := (&PackageVersionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withVersions = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SoftwarePackage.Query().
//		GroupBy(softwarepackage.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SoftwarePackageQuery) GroupBy(field string, fields ...string) *SoftwarePackageGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SoftwarePackageGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = softwarepackage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.SoftwarePackage.Query().
//		Select(softwarepackage.FieldName).
//		Scan(ctx, &v)
func (_q *SoftwarePackageQuery) Select(fields ...string) *SoftwarePackageSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SoftwarePackageSelect{SoftwarePackageQuery: _q}
	sbuild.label = softwarepackage.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SoftwarePackageSelect configured with the given aggregations.
func (_q *SoftwarePackageQuery) Aggregate(fns ...AggregateFunc) *SoftwarePackageSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SoftwarePackageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !softwarepackage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SoftwarePackageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SoftwarePackage, error) {
	var (
		nodes       = []*SoftwarePackage{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withVersions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SoftwarePackage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SoftwarePackage{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withVersions; query != nil {
		if err := _q.loadVersions(ctx, query, nodes,
			func(n *SoftwarePackage) { n.Edges.Versions = []*PackageVersion{} },
			func(n *SoftwarePackage, e *PackageVersion) { n.Edges.Versions = append(n.Edges.Versions, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *SoftwarePackageQuery) loadVersions(ctx context.Context, query *PackageVersionQuery, nodes []*SoftwarePackage, init func(*SoftwarePackage), assign func(*SoftwarePackage, *PackageVersion)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*SoftwarePackage)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.PackageVersion(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(softwarepackage.VersionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.software_package_versions
		if fk == nil {
			return fmt.Errorf(`foreign-key "software_package_versions" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "software_package_versions" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *SoftwarePackageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SoftwarePackageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(softwarepackage.Table, softwarepackage.Columns, sqlgraph.NewFieldSpec(softwarepackage.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, softwarepackage.FieldID)
		for i := range fields {
			if fields[i] != softwarepackage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SoftwarePackageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(softwarepackage.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = softwarepackage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SoftwarePackageGroupBy is the group-by builder for SoftwarePackage entities.
type SoftwarePackageGroupBy struct {
	selector
	build *SoftwarePackageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SoftwarePackageGroupBy) Aggregate(fns ...AggregateFunc) *SoftwarePackageGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SoftwarePackageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SoftwarePackageQuery, *SoftwarePackageGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SoftwarePackageGroupBy) sqlScan(ctx context.Context, root *SoftwarePackageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SoftwarePackageSelect is the builder for selecting fields of SoftwarePackage entities.
type SoftwarePackageSelect struct {
	*SoftwarePackageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SoftwarePackageSelect) Aggregate(fns ...AggregateFunc) *SoftwarePackageSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SoftwarePackageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SoftwarePackageQuery, *SoftwarePackageSelect](ctx, _s.SoftwarePackageQuery, _s, _s.inters, v)
}

func (_s *SoftwarePackageSelect) sqlScan(ctx context.Context, root *SoftwarePackageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
