// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/d4t4l0r3/partial-mirror/ent/predicate"
	"github.com/d4t4l0r3/partial-mirror/ent/softwarepackage"
)

// SoftwarePackageDelete is the builder for deleting a SoftwarePackage entity.
type SoftwarePackageDelete struct {
	config
	hooks    []Hook
	mutation *SoftwarePackageMutation
}

// Where appends a list predicates to the SoftwarePackageDelete builder.
func (_d *SoftwarePackageDelete) Where(ps ...predicate.SoftwarePackage) *SoftwarePackageDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SoftwarePackageDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SoftwarePackageDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SoftwarePackageDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(softwarepackage.Table, sqlgraph.NewFieldSpec(softwarepackage.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SoftwarePackageDeleteOne is the builder for deleting a single SoftwarePackage entity.
type SoftwarePackageDeleteOne struct {
	_d *SoftwarePackageDelete
}

// Where appends a list predicates to the SoftwarePackageDelete builder.
func (_d *SoftwarePackageDeleteOne) Where(ps ...predicate.SoftwarePackage) *SoftwarePackageDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SoftwarePackageDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{softwarepackage.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SoftwarePackageDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
