// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// PackageVersion is the predicate function for packageversion builders.
type PackageVersion func(*sql.Selector)

// SoftwarePackage is the predicate function for softwarepackage builders.
type SoftwarePackage func(*sql.Selector)
